title: 'Scienze Filosofiche Unimi'
description: "Una raccolta di gruppi whatsapp della facoltà di Scienze Filosofiche di Unimi"
baseurl:
url:

header_pages:
  - index.md
  - about.md

style: dark

footer: 'Per qualsiasi modifica: <a href="https://github.com/Darmstadtio/SF_Unimi.github.io">Github</a> o <a href="https://t.me/darmstadtio">Telegram</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
